{
  parserClass="app.softwork.kobol.CobolParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Cobol"
  psiImplClassSuffix="Impl"
  psiPackage="app.softwork.kobol"
  psiImplPackage="app.softwork.kobol.impl"

  elementTypeHolderClass="app.softwork.kobol.CobolTypes"
  elementTypeClass="app.softwork.kobol.CobolElementType"
  tokenTypeClass="app.softwork.kobol.CobolTokenType"

  tokens=[
    lineNumber="regexp:\r?\n\d{6}(\s|\*)"
    varName="regexp:[a-zA-Z]([\w|-]+[\w|_])*"
    space="regexp:\s+"
    comment="regexp:\*.*\r?\n\d{6}(\s|\*)"
    number="regexp:\d+(\.\d*)?"
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
    any="regexp:.*\."
    twoDigits="regexp:\d{2}"
  ]

//  extends(".*_file")=file
}

//root ::= root_item *
//private root_item ::= !<<eof>> exps '.' {pin=1 recoverWhile=exps_recover}
root ::= program

program ::= comments idDiv [envDiv] [dataDiv] procedureDiv

comments ::= (comment) *

DOT ::= '.'
LP ::= '('
RP ::= ')'


idDiv ::= identification division DOT programID [other]
identification ::= 'IDENTIFICATION'
division ::= 'DIVISION'

private other ::= (author | installation | date ) *

programID ::= comments 'PROGRAM-ID' [DOT] varName DOT
author ::= comments 'AUTHOR' anys
installation ::= comments 'INSTALLATION' anys
date ::= comments 'DATE-WRITTEN' anys

anys ::= any *

envDiv ::=  comments environment division DOT [config] [input]
environment ::= 'ENVIRONMENT'
configuration ::= 'CONFIGURATION'
config ::= comments configuration section DOT [specialNames]
specialNamesLiteral ::= 'SPECIAL-NAMES'
specialNames ::= comments specialNamesLiteral DOT [specialNameDeclaration* DOT]
specialNameDeclaration ::= comments specialName
specialName ::= specialNameEnv is specialNameValue
specialNameEnv ::= varName
specialNameValue ::= varName
is ::= 'IS'

inputOutputLiteral ::= 'INPUT-OUTPUT'
input ::= comments inputOutputLiteral section DOT [fileControl]
fileControlLiteral ::= 'FILE-CONTROL'
fileControl ::= comments fileControlLiteral DOT [fileConfig*]
fileConfig ::= comments fileConfigSelect fileConfigAssign fileConfigStatus DOT
fileConfigSelectLiteral ::= 'SELECT'
fileConfigSelect ::= fileConfigSelectLiteral varName
fileConfigAssignLiteral ::= 'ASSIGN'
fileConfigAssign ::= fileConfigAssignLiteral [to] varName
fileLiteral ::= 'FILE'
fileConfigStatusStatusLiteral ::= 'STATUS'
fileConfigStatus ::= fileLiteral fileConfigStatusStatusLiteral varName
section ::= 'SECTION'

dataDiv ::= comments data division DOT comments [fileSection] [workingStorageSection]
data ::= 'DATA'

fileSection ::= comments fileLiteral section DOT fileDescriptions*
fd ::= 'FD'
recordingLiteral ::= 'RECORDING'
labelLiteral ::= 'LABEL'
blockLiteral ::= 'BLOCK'
recordLiteral ::= 'RECORD'
standard ::= 'STANDARD'
recording ::= recordingLiteral varName
block ::= blockLiteral varName
fileRecord ::= recordLiteral varName
label ::= labelLiteral recordLiteral standard
fileDescriptions ::= fileDescription | (record*)
fileDescription ::= comments fd varName recording [block] [fileRecord] label dataRecord DOT
dataRecord ::= data recordLiteral varName

workingStorageSection ::= workingStorage section DOT (record) *
workingStorage ::= 'WORKING-STORAGE'

value ::= 'VALUE'
record ::= comments number varName [pic] [value var] [COMP] DOT
COMP ::= 'COMP'
pic ::= picLiteral (picXA | [picS] pic9) [LP number RP]
picLiteral ::= 'PIC'
picXA ::= 'X' | 'A'
picS ::= 'S'
pic9 ::= '9'

procedureDiv ::= comments procedure division DOT [sentence*] [procedureSection*]
procedure ::= 'PROCEDURE'
procedureSection ::= comments varName section DOT sentence
sentence ::= procedures+ DOT
procedures ::= comments (display | moving | performing)
performing ::= perform varName
perform ::= 'PERFORM'
moving ::= move expr to varName
move ::= 'MOVE'
to ::= 'TO'

expr ::= (var | varName | stringConcat)

var ::= string | number

displayLiteral ::= 'DISPLAY'
display ::= displayLiteral stringConcat
stringConcat ::= (string | varName) +
