formatting:
  NoWildcardImports:
    active: false
  Filename:
    active: false
  TrailingCommaOnDeclarationSite:
    active: true
  TrailingCommaOnCallSite:
    active: true

style:
  WildcardImport:
    active: false
  CollapsibleIfStatements:
    active: true
  DataClassShouldBeImmutable:
    active: true
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    max: 10
  LoopWithTooManyJumpStatements:
    maxJumpCount: 5

naming:
  MemberNameEqualsClassName:
    active: false

potential-bugs:
  UnsafeCallOnNullableType:
    active: false

complexity:
  active: false
