name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/gradle-build-action@dependency-graph
        with:
          dependency-graph: generate-and-submit
      - run: ./gradlew assemble compileTestKotlin
      - name: Build with Gradle
        run: ./gradlew build
      - run: ./gradlew -Pversion=42.0.0 runPluginVerifier
