name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    env:
      ORG_GRADLE_PROJECT_GitHubPackagesUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_GitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build
      - run: ./gradlew -Pversion=42.0.0 runPluginVerifier
