name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
          gradle-home-cache-cleanup: true
      - run: ./gradlew assemble compileTestKotlin
      - name: Build with Gradle
        run: ./gradlew build
      - name: Detekt
        run: ./gradlew detekt
        if: success() || failure()
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
      - run: ./gradlew -Pversion=42.0.0 runPluginVerifier
