name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: ./gradlew build

      - name: Detekt
        run: ./gradlew :detekt
        if: always()
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif

  verify:
    runs-on: ubuntu-24.04-arm
    needs: build

    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew -Pversion=42.0.0 :intellij-plugin:verifyPlugin
