name: GH

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/github-script@v6
        id: my-releases
        with:
          result-encoding: string
          retries: 3
          script: |
            return github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1000
            });
      - run: echo "${{ steps.my-releases.outputs.result }}"
