name: Release

on:
  release:
    types: [created]

concurrency:
  group: "cd"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Publish
        run: ./gradlew -Pversion=$version publish :closeAndReleaseStagingRepositories
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONARTYPE_APIKEY }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONARTYPE_APITOKEN }}
      - run: ./gradlew -Pversion=$version :intellij-plugin:createPluginRepo
      - uses: actions/upload-pages-artifact@v3
        with:
          path: intellij-plugin/build/customRepo
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
