name: Release

on:
  release:
    types: [ created ]

concurrency:
  group: "cd"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_OUTPUT
        id: version
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: gradle/actions/setup-gradle@v4

      - name: Publish
        run: ./gradlew -Pversion=${{ steps.version.outputs.version }} publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PASSWORD }}
      - run: ./gradlew -Pversion=${{ steps.version.outputs.version }} :intellij-plugin:createPluginRepo
      - uses: actions/upload-pages-artifact@v3
        with:
          path: intellij-plugin/build/customRepo
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
